name: pam
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - comm=0.2.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - debugpy=1.8.6
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.13.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libsodium=1.0.20
  - libstdcxx=14.1.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - llvm-openmp=14.0.6
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.3
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.11.9
  - python_abi=3.11
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - sympy=1.13.2
  - tbb=2021.8.0
  - tk=8.6.14
  - torchtriton=2.3.0
  - tornado=6.4.1
  - traitlets=5.14.3
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==1.3.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.8
      - aiosignal==1.3.1
      - alignscore==0.1.3
      - amrlib==0.8.0
      - annotated-types==0.7.0
      - attrs==24.2.0
      - bert-score==0.3.13
      - blis==1.2.1
      - catalogue==2.0.10
      - certifi==2024.8.30
      - cffi==1.15.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.20.0
      - confection==0.1.5
      - contourpy==1.3.0
      - cycler==0.12.1
      - cymem==2.0.10
      - datasets==2.21.0
      - dill==0.3.8
      - en-core-web-md==3.8.0
      - evaluate==0.4.3
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gensim==4.3.3
      - grpcio==1.71.0
      - huggingface-hub==0.25.1
      - idna==3.10
      - joblib==1.4.2
      - jsonlines==2.0.0
      - kiwisolver==1.4.7
      - langcodes==3.5.0
      - language-data==1.3.0
      - lightning-utilities==0.14.3
      - marisa-trie==1.2.1
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mip==1.15.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - murmurhash==1.0.11
      - nltk==3.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - pandas==2.2.3
      - penman==1.3.1
      - pillow==10.4.0
      - preshed==3.0.9
      - protobuf==3.20.0
      - pyarrow==17.0.0
      - pycparser==2.22
      - pydantic==2.10.2
      - pydantic-core==2.27.1
      - pyemd==1.0.0
      - pyg-lib==0.4.0+pt23cu118
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.9.5
      - pytz==2024.2
      - regex==2024.9.11
      - requests==2.32.3
      - rich==13.9.4
      - rouge-score==0.1.2
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - sentence-transformers==3.1.1
      - shellingham==1.5.4
      - smart-open==7.0.5
      - smatch==1.0.4
      - smatchpp==1.5.1
      - spacy==3.8.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - thinc==8.3.4
      - threadpoolctl==3.5.0
      - tokenizers==0.20.0
      - torch==1.13.1
      - torch-cluster==1.6.3+pt23cu118
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt23cu118
      - torch-sparse==0.6.18+pt23cu118
      - torch-spline-conv==1.2.2+pt23cu118
      - torchmetrics==1.5.2
      - tqdm==4.66.5
      - transformers==4.45.1
      - typer==0.13.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - unidecode==1.3.8
      - urllib3==2.2.3
      - wasabi==1.1.3
      - weasel==0.4.1
      - werkzeug==3.1.3
      - wrapt==1.17.0
      - xxhash==3.5.0
      - yarl==1.13.1
